modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/Kotori316/FlexibleMarker/issues"
[[mods]] 
modId="flexiblemarker"
version="${file.jarVersion}"
displayName="FlexibleMarker"
credits="Kotori316"
authors="Kotori316"
displayURL="https://github.com/Kotori316/FlexibleMarker"
description='''
This mod adds a marker, which can change the area by GUI.
'''
[[dependencies.flexiblemarker]]
    modId="forge" 
    mandatory=true 
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flexiblemarker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,)"
    ordering="NONE"
    side="BOTH"