name: Build Check

on:
  push:
    branches:
      - "master"
    tags:
      - "!*"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle15-${{ hashFiles('**/forge_version.properties') }}
      - name: Compile and Build
        run: chmod +x ./gradlew && ./gradlew build --continue --warning-mode all
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
